[id="Troubleshooting_Sync_Errors_{context}"]
= Troubleshooting Sync Errors

"[Errno 1] Operation not permitted: ..." during repository syncing::

[options="nowrap" subs="+quotes,attributes"]
----
# chown --recursive pulp.pulp /var/lib/pulp/media/
----

"{“policy”:[""" is not a valid choice."]}" during Debian repository syncing::

[options="nowrap" subs="+quotes,attributes"]
----
# foreman-rake katello:migrate_deb_content_attributes_to_pulp3
----

500 API error during syncing with "cryptography.fernet.InvalidToken" in /var/log/messages traceback::

Run this on the Katello server and every smart proxy.
+
[options="nowrap" subs="+quotes,attributes"]
----
# sudo -u pulp PULP_SETTINGS='/etc/pulp/settings.py' pulpcore-manager datarepair-2327 --dry-run
----
+
If you see values greater than 0 returned from the dry-run:
+
[options="nowrap" subs="+quotes,attributes"]
----
# sudo -u pulp PULP_SETTINGS='/etc/pulp/settings.py' pulpcore-manager datarepair-2327
----
